kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins
  namespace: sa-space
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
# - apiGroups: [""]
#   resources: ["pods","namespaces","deployments"]
#   verbs: ["create","delete","get","list","patch","update","watch"]
# - apiGroups: [""]
#   resources: ["pods/exec"]
#   verbs: ["create","delete","get","list","patch","update","watch"]
# - apiGroups: [""]
#   resources: ["pods/log"]
#   verbs: ["get","list","watch"]
# - apiGroups: [""]
#   resources: ["secrets"]
#   verbs: ["get"]
