apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  namespace: sa-space
secrets:
  - name: sa-token
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: sa-secret
  namespace: sa-space
  annotations:
    kubernetes.io/service-account.name: "sa"
