---
apiVersion: v1
kind: Service
metadata:
  name: market-data-service
  labels: 
    app: market-data 
  namespace: example
spec:
  type: NodePort
  selector:
    app: market-data
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      # nodePort: 30623
  type: LoadBalancer
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#     name: market-data-ingress
#     namespace: example
# spec:
#     rules:
#         - host: frontend.example.local
#           http:
#             paths:
#               - backend:
#                   service:
#                       name: market-data-service
#                       port:
#                         number: 80
#                 pathType: Prefix
#                 path: /
